name: Docker Image CI
on: 
  workflow_dispatch:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    if: 
    steps:
    - uses: actions/checkout@v4
    - name: Install git
      run: sudo apt-get install git
    - name: Quay login
      uses: docker/login-action@v3.1.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Build images
      run: make all

